# -*- coding: utf-8 -*-
"""TOA_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NGRw4ubSXqgcEVss8qhT1Zf_Jyj-s1hB
"""



import nltk
from nltk import CFG

class PDASimulator:
    def __init__(self):
        self.grammar = {
    "S": [["NP", "VP"],["NP"]],
    "NP": [
        ["SingularPronoun"], ["PluralPronoun"], ["SingularNoun"], ["PluralNoun"],
        ["Article", "SingularNoun"], ["Article", "PluralNoun"],
        ["Adjective", "SingularNoun"], ["Adjective", "PluralNoun"],
        ["Adjective", "Article", "SingularNoun"], ["Adjective", "Article", "PluralNoun"],
        ["Article", "Adjective", "SingularNoun"], ["Article", "Adjective", "PluralNoun"]
    ],
    "VP": [
        ["SingularVerb"], ["PluralVerb"],
        ["SingularAux", "VerbING"], ["PluralAux", "VerbING"],
        ["SingularVerb", "NP"], ["PluralVerb", "NP"],
        ["SingularAux", "VerbING", "NP"], ["PluralAux", "VerbING", "NP"],
        ["SingularAux", "VerbING", "Adverb"], ["PluralAux", "VerbING", "Adverb"],
        ["SingularAux", "Adverb", "VerbING"],
        ["PluralAux", "Adverb", "VerbING"],
        ["pastparticipleAUXS", "PastParticiple"], ["pastparticipleAUXP", "PastParticiple"],
        ["pastparticipleAUXS", "PastParticiple","NP"], ["pastparticipleAUXP", "PastParticiple", "NP"],
        ["NP","pastparticipleAUXS", "PastParticiple","NP"], ["NP","pastparticipleAUXP", "PastParticiple", "NP"],
        ["NP","pastparticipleAUXS", "PastParticiple","Article","NP"], ["NP","pastparticipleAUXP", "PastParticiple","Article", "NP"],
        ["NP","pastparticipleAUXS", "PastParticiple"], ["NP","pastparticipleAUXP", "PastParticiple"],
        ["SingularVerb", "Adverb"], ["PluralVerb", "Adverb"],
        ["pastparticipleAUXS", "PastParticiple", "Adverb"], ["pastparticipleAUXP", "PastParticiple", "Adverb"],
        ["pastparticipleAUXS", "PastParticiple", "NP", "Adverb"], ["pastparticipleAUXP", "PastParticiple", "NP", "Adverb"],
        ["Article", "Adjective", "SingularNoun", "pastparticipleAUXS", "PastParticiple"],["Article", "Adjective", "SingularNoun", "pastparticipleAUXS", "PastParticiple"],
        ["SingularVerb"], ["PluralVerb"],
        ["SingularAux", "VerbING"], ["PluralAux", "VerbING"],
        ["pastparticipleAUXS", "PastParticiple"],
        ["pastparticipleAUXP", "PastParticiple"],
        ["pastparticipleAUXS", "PastParticiple", "NP"],
        ["pastparticipleAUXP", "PastParticiple", "NP"],
        ["pastparticipleAUXS", "PastParticiple", "Adjective", "PluralNoun"],
        ["pastparticipleAUXP", "PastParticiple", "Adjective", "PluralNoun"],
        ["pastparticipleAUXS", "PastParticiple", "Adverb"],
        ["pastparticipleAUXP", "PastParticiple", "Adverb"],
        ["SingularVerb", "NP"], ["PluralVerb", "NP"],
        ["SingularAux", "VerbING", "NP"], ["PluralAux", "VerbING", "NP"],
        ["pastparticipleAUXS", "Adverb", "PastParticiple"],
        ["pastparticipleAUXP", "Adverb", "PastParticiple"],
        ["SingularNoun", "SingularAux", "PastParticiple"],
        ["SingularNoun", "NP", "PastParticiple"],
        ["SingularNoun", "pastparticipleAUXS", "PastParticiple"],
        ["SingularNoun", "pastparticipleAUXP", "PastParticiple"]
    ],
    "SingularPronoun": [["he"], ["she"], ["it"]],
    "PluralPronoun": [["they"]],
    "SingularNoun": [["John"], ["Mary"], ["dog"], ["cat"], ["water"], ["bread"], ["juice"], ["milk"], ["house"], ["car"], ["apple"]],
    "PluralNoun": [["dogs"], ["cats"], ["waters"], ["breads"], ["juices"], ["milks"], ["houses"], ["cars"], ["apples"]],
    "SingularVerb": [
        ["eats"], ["runs"], ["jumps"], ["sees"],
        ["writes"], ["reads"], ["drinks"], ["speaks"], ["sleeps"],
        ["creates"], ["builds"], ["loves"], ["hates"], ["helps"], ["catches"], ["throws"], ["finds"], ["loses"],
        ["draws"], ["paints"], ["teaches"], ["studies"], ["laughs"], ["cries"], ["sings"], ["dances"], ["climbs"], ["runs"],
        ["thinks"], ["believes"], ["knows"], ["understands"], ["makes"], ["fixes"], ["writes"], ["plays"], ["touches"],
        ["picks"], ["puts"], ["takes"], ["remembers"], ["forgets"], ["helps"], ["pushes"], ["pulls"], ["shakes"],
        ["bakes"], ["cooks"], ["drives"], ["rides"], ["buys"], ["sells"], ["lends"], ["borrows"], ["steals"],
        ["builds"], ["tears"], ["opens"], ["closes"], ["runs"], ["walks"], ["sits"], ["stands"], ["rests"], ["jumps"],
        ["works"], ["sleeps"], ["waits"], ["hopes"], ["dreams"], ["tears"], ["touches"], ["moves"], ["speaks"],
        ["reads"], ["writes"], ["reflects"], ["looks"], ["sees"], ["thinks"], ["listens"], ["hears"]
    ],
    "PluralVerb": [
        ["eat"], ["run"], ["jump"], ["see"],
        ["write"], ["read"], ["drink"], ["speak"], ["sleep"],
        ["create"], ["build"], ["love"], ["hate"], ["help"], ["catch"], ["throw"], ["find"], ["lose"],
        ["draw"], ["paint"], ["teach"], ["study"], ["laugh"], ["cry"], ["sing"], ["dance"], ["climb"], ["run"],
        ["think"], ["believe"], ["know"], ["understand"], ["make"], ["fix"], ["write"], ["play"], ["touch"],
        ["pick"], ["put"], ["take"], ["remember"], ["forget"], ["help"], ["push"], ["pull"], ["shake"],
        ["bake"], ["cook"], ["drive"], ["ride"], ["buy"], ["sell"], ["lend"], ["borrow"], ["steal"],
        ["build"], ["tear"], ["open"], ["close"], ["run"], ["walk"], ["sit"], ["stand"], ["rest"], ["jump"],
        ["work"], ["sleep"], ["wait"], ["hope"], ["dream"], ["tear"], ["touch"], ["move"], ["speak"],
        ["read"], ["write"], ["reflect"], ["look"], ["see"], ["think"], ["listen"], ["hear"]
    ],
    "VerbING": [
        ["eating"], ["running"], ["jumping"], ["seeing"],
        ["writing"], ["reading"], ["drinking"], ["speaking"], ["sleeping"],
        ["creating"], ["building"], ["loving"], ["hating"], ["helping"], ["catching"], ["throwing"], ["finding"], ["losing"],
        ["drawing"], ["painting"], ["teaching"], ["studying"], ["laughing"], ["crying"], ["singing"], ["dancing"], ["climbing"], ["running"],
        ["thinking"], ["believing"], ["knowing"], ["understanding"], ["making"], ["fixing"], ["writing"], ["playing"], ["touching"],
        ["picking"], ["putting"], ["taking"], ["remembering"], ["forgetting"], ["helping"], ["pushing"], ["pulling"], ["shaking"],
        ["baking"], ["cooking"], ["driving"], ["riding"], ["buying"], ["selling"], ["lending"], ["borrowing"], ["stealing"],
        ["building"], ["tearing"], ["opening"], ["closing"], ["running"], ["walking"], ["sitting"], ["standing"], ["resting"], ["jumping"],
        ["working"], ["sleeping"], ["waiting"], ["hoping"], ["dreaming"], ["tearing"], ["touching"], ["moving"], ["speaking"],
        ["reading"], ["writing"], ["reflecting"], ["looking"], ["seeing"], ["thinking"], ["listening"], ["hearing"]
    ],
    "PastParticiple": [
        ["eaten"], ["run"], ["jumped"], ["seen"],
        ["written"], ["read"], ["drunk"], ["spoken"], ["slept"],
        ["created"], ["built"], ["loved"], ["hated"], ["helped"], ["caught"], ["thrown"], ["found"], ["lost"],
        ["drawn"], ["painted"], ["taught"], ["studied"], ["laughed"], ["cried"], ["sung"], ["danced"], ["climbed"], ["run"],
        ["thought"], ["believed"], ["known"], ["understood"], ["made"], ["fixed"], ["written"], ["played"], ["touched"],
        ["picked"], ["put"], ["taken"], ["remembered"], ["forgotten"], ["helped"], ["pushed"], ["pulled"], ["shaken"],
        ["baked"], ["cooked"], ["driven"], ["ridden"], ["bought"], ["sold"], ["lent"], ["borrowed"], ["stolen"],
        ["built"], ["torn"], ["opened"], ["closed"], ["run"], ["walked"], ["sat"], ["stood"], ["rested"], ["jumped"],
        ["worked"], ["slept"], ["waited"], ["hoped"], ["dreamed"], ["torn"], ["touched"], ["moved"], ["spoken"],
        ["read"], ["written"], ["reflected"], ["looked"], ["seen"], ["thought"], ["listened"], ["heard"]
    ],
    "SingularAux": [["is"]],
    "PluralAux": [["are"]],
    "Article": [["a"], ["an"], ["the"]],
    "pastparticipleAUXS": [["has"]],
    "pastparticipleAUXP": [["have"]],

    "Adjective": [
        ["big"], ["small"], ["beautiful"], ["ugly"], ["fast"], ["slow"], ["happy"], ["sad"],
        ["young"], ["old"], ["new"], ["good"], ["bad"], ["easy"], ["hard"], ["bright"], ["dark"],
        ["strong"], ["weak"], ["clean"], ["dirty"], ["expensive"], ["cheap"], ["tall"], ["short"],
        ["intelligent"], ["funny"], ["kind"], ["rude"], ["generous"], ["selfish"], ["rich"], ["poor"], ["tired"]
    ],

    "Adverb":[["quickly"], ["slowly"], ["silently"], ["loudly"], ["happily"], ["sadly"],
         ["easily"], ["hardly"], ["brightly"], ["darkly"], ["strongly"], ["weakly"],
         ["cleanly"], ["dirtily"], ["expensively"], ["cheaply"], ["intelligently"],
         ["funny"], ["kindly"], ["rudely"], ["generously"], ["selfishly"], ["beautifully"]]



}




        self.terminals = {
    "he", "she", "it", "they",
    "John", "Mary", "dog", "cat", "dogs", "cats", "water", "bread", "juice", "milk", "house", "car","apples","apple",
    "eats", "runs", "jumps", "sees", "eat", "run", "jump", "see",
    "writes", "reads", "drinks", "speaks", "sleeps", "write", "read", "drink", "speak", "sleep",
    "creates", "builds", "loves", "hates", "helps", "catches", "throws", "finds", "loses",
    "create", "build", "love", "hate", "help", "catch", "throw", "find", "lose",
    "draws", "paints", "teaches", "studies", "laughs", "cries", "sings", "dances", "climbs", "thinks", "believes",
    "knows", "understands", "makes", "fixes", "plays", "touches", "picks", "puts", "takes", "remembers", "forgets",
    "pushes", "pulls", "shakes", "bakes", "cooks", "drives", "rides", "buys", "sells", "lends", "borrows", "steals",
    "builds", "tears", "opens", "closes", "walks", "sits", "stands", "rests", "waits", "hopes", "dreams",
    "works", "waits", "reflects", "looks", "listens", "hears", "eating", "running", "jumping", "seeing",
    "writing", "reading", "drinking", "speaking", "sleeping", "creating", "building", "loving", "hating", "helping",
    "catching", "throwing", "finding", "losing", "drawing", "painting", "teaching", "studying", "laughing", "crying",
    "singing", "dancing", "climbing", "thinking", "believing", "knowing", "understanding", "making", "fixing", "playing",
    "touching", "picking", "putting", "taking", "remembering", "forgetting", "helping", "pushing", "pulling", "shaking",
    "baking", "cooking", "driving", "riding", "buying", "selling", "lending", "borrowing", "stealing", "building",
    "tearing", "opening", "closing", "running", "walking", "sitting", "standing", "resting", "jumping", "working", "sleeping",
    "waiting", "hoping", "dreaming", "tearing", "touching", "moving", "speaking", "reading", "writing", "reflecting",
    "looking", "seeing", "thinking", "listening", "hearing", "eaten", "run", "jumped", "seen", "written", "read", "drunk",
    "spoken", "slept", "created", "built", "loved", "hated", "helped", "caught", "thrown", "found", "lost", "drawn",
    "painted", "taught", "studied", "laughed", "cried", "sung", "danced", "climbed", "thought", "believed", "known",
    "understood", "made", "fixed", "played", "touched", "picked", "put", "taken", "remembered", "forgotten", "helped",
    "pushed", "pulled", "shaken", "baked", "cooked", "driven", "ridden", "bought", "sold", "lent", "borrowed", "stolen",
    "built", "torn", "opened", "closed", "walked", "sat", "stood", "rested", "jumped", "worked", "slept", "waited",
    "hoped", "dreamed", "torn", "touched", "moved", "spoken", "read", "written", "reflected", "looked", "seen", "thought",
    "listened", "heard", "is", "are", "a", "an", "the","has","have",
    # Adjectives
    "big", "small", "young", "old", "fast", "slow", "heavy", "light", "beautiful", "ugly", "tall", "short", "long", "wide",
    "narrow", "hot", "cold", "soft", "hard", "clean", "dirty", "strong", "weak", "good", "bad", "happy", "sad", "rich", "poor",
    "smart", "stupid", "quiet", "loud", "friendly", "unfriendly", "warm", "cool", "bright", "dark", "tired", "beautifully", "quickly", "slowly", "silently", "loudly", "happily", "sadly",
    "easily", "hardly", "brightly", "darkly", "strongly", "weakly", "cleanly", "dirtily", "expensively", "cheaply", "intelligently", "funny", "kindly", "rudely", "generously", "selfishly"
    }
    def parse(self, tokens):
        return self._parse(tokens, ["S"], [], None)

    def _parse(self, tokens, stack, trace, subject_number):
      if not tokens and not stack:
        return True
      if not stack or (not tokens and stack):
        return False

      top = stack.pop()

      if top in self.terminals:
         if tokens and top == tokens[0]:
            return self._parse(tokens[1:], stack.copy(), trace, subject_number)
         else:
            return False
      elif top in self.grammar:
         for production in self.grammar[top]:
            new_stack = stack.copy() + list(reversed(production))
            new_subject_number = subject_number

            # Handle NP to determine subject number
            if top == "NP":
                if production[0] in ["SingularPronoun", "SingularNoun"]:
                    new_subject_number = "singular"
                elif production[0] in ["PluralPronoun", "PluralNoun"]:
                    new_subject_number = "plural"

            # Handle VP verb agreement
            if top == "VP":
                # First check if we have any verb forms in this production
                verb_categories = {
                    "singular": {"SingularVerb", "SingularAux", "pastparticipleAUXS"},
                    "plural": {"PluralVerb", "PluralAux", "pastparticipleAUXP"}
                }

                # Find all verb-related symbols in this production
                verb_symbols = [sym for sym in production
                               if sym in verb_categories["singular"] or sym in verb_categories["plural"]]

                if verb_symbols and subject_number:
                    # Check if any verb form matches the subject number
                    valid = any(
                        (subject_number == "singular" and sym in verb_categories["singular"]) or
                        (subject_number == "plural" and sym in verb_categories["plural"])
                        for sym in verb_symbols
                    )
                    if not valid:
                        continue  # Skip this production if no matching verb form

            # Recursive call for all cases
            if self._parse(tokens[:], new_stack, trace + [top], new_subject_number):
                return True
         return False
      else:
        return False


nltk_grammar = CFG.fromstring("""
    S -> NP VP
    S -> Article Adjective PluralNoun pastparticipleAUXP PastParticiple
    S -> Article Adjective SingularNoun pastparticipleAUXS PastParticiple
    NP -> SingularPronoun | PluralPronoun | SingularNoun | PluralNoun
    NP -> Article SingularNoun | Article PluralNoun
    NP -> Adjective SingularNoun | Adjective PluralNoun
    NP -> Adjective Article SingularNoun | Adjective Article PluralNoun
    VP -> SingularVerb | PluralVerb
    VP -> SingularAux VerbING | PluralAux VerbING
    VP -> SingularVerb NP | PluralVerb NP
    VP -> SingularAux VerbING NP | PluralAux VerbING NP
    VP -> pastparticipleAUXS PastParticiple | pastparticipleAUXP PastParticiple
    VP -> pastparticipleAUXS PastParticiple NP | pastparticipleAUXP PastParticiple NP
    VP -> SingularVerb Adverb | PluralVerb Adverb
    VP -> pastparticipleAUXS PastParticiple Adverb | pastparticipleAUXP PastParticiple Adverb
    VP -> pastparticipleAUXS PastParticiple NP Adverb | pastparticipleAUXP PastParticiple NP Adverb
    VP -> NP pastparticipleAUXS PastParticiple NP |NP pastparticipleAUXP PastParticiple NP
    VP -> NP pastparticipleAUXS PastParticiple Article NP |NP pastparticipleAUXP PastParticiple Article NP
    VP -> NP pastparticipleAUXS PastParticiple  |NP pastparticipleAUXP PastParticiple
    VP -> NP pastparticipleAUXS PastParticiple Adverb |NP pastparticipleAUXP PastParticiple Adverb
    VP -> pastparticipleAUXS PastParticiple NP
    VP -> pastparticipleAUXP PastParticiple NP
    VP -> pastparticipleAUXS PastParticiple Adjective PluralNoun
    VP -> pastparticipleAUXP PastParticiple Adjective PluralNoun
    VP -> pastparticipleAUXS PastParticiple Adverb
    VP -> pastparticipleAUXP PastParticiple Adverb
    VP -> pastparticipleAUXS Adverb PastParticiple
    VP -> pastparticipleAUXP Adverb PastParticiple
    VP -> SingularNoun SingularAux PastParticiple
    VP -> SingularNoun NP PastParticiple
    VP -> SingularNoun pastparticipleAUXS PastParticiple
    VP -> SingularNoun pastparticipleAUXP PastParticiple
    VP -> SingularAux VerbING Adverb
    VP -> PluralAux VerbING Adverb
    VP -> SingularAux Adverb VerbING
    VP -> PluralAux Adverb VerbING



    SingularPronoun -> 'he' | 'she' | 'it'
    PluralPronoun -> 'they'
    SingularNoun -> 'John' | 'Mary' | 'dog' | 'cat' | 'water' | 'bread' | 'juice' | 'milk' | 'house' | 'car' | 'apple'
    PluralNoun -> 'dogs' | 'cats' | 'waters' | 'breads' | 'juices' | 'milks' | 'houses' | 'cars' | 'apples'
    SingularVerb -> 'eats' | 'runs' | 'jumps' | 'sees' | 'writes' | 'reads' | 'drinks' | 'speaks' | 'sleeps' | 'creates' | 'builds' | 'loves' | 'hates' | 'helps' | 'catches' | 'throws' | 'finds' | 'loses' | 'draws' | 'paints' | 'teaches' | 'studies' | 'laughs' | 'cries' | 'sings' | 'dances' | 'climbs' | 'thinks' | 'believes' | 'knows' | 'understands' | 'makes' | 'fixes' | 'plays' | 'touches' | 'picks' | 'puts' | 'takes' | 'remembers' | 'forgets' | 'pushes' | 'pulls' | 'shakes' | 'bakes' | 'cooks' | 'drives' | 'rides' | 'buys' | 'sells' | 'lends' | 'borrows' | 'steals' | 'builds' | 'tears' | 'opens' | 'closes' | 'walks' | 'sits' | 'stands' | 'rests' | 'waits' | 'hopes' | 'dreams' | 'works' | 'reflects' | 'looks' | 'listens' | 'hears'
    PluralVerb -> 'eat' | 'run' | 'jump' | 'see' | 'write' | 'read' | 'drink' | 'speak' | 'sleep' | 'create' | 'build' | 'love' | 'hate' | 'help' | 'catch' | 'throw' | 'find' | 'lose' | 'draw' | 'paint' | 'teach' | 'study' | 'laugh' | 'cry' | 'sing' | 'dance' | 'climb' | 'think' | 'believe' | 'know' | 'understand' | 'make' | 'fix' | 'play' | 'touch' | 'pick' | 'put' | 'take' | 'remember' | 'forget' | 'push' | 'pull' | 'shake' | 'bake' | 'cook' | 'drive' | 'ride' | 'buy' | 'sell' | 'lend' | 'borrow' | 'steal' | 'tear' | 'open' | 'close' | 'walk' | 'sit' | 'stand' | 'rest' | 'wait' | 'hope' | 'dream' | 'move' | 'reflect' | 'look' | 'listen' | 'hear'
    VerbING -> 'eating' | 'running' | 'jumping' | 'seeing' | 'writing' | 'reading' | 'drinking' | 'speaking' | 'sleeping' | 'creating' | 'building' | 'loving' | 'hating' | 'helping' | 'catching' | 'throwing' | 'finding' | 'losing' | 'drawing' | 'painting' | 'teaching' | 'studying' | 'laughing' | 'crying' | 'singing' | 'dancing' | 'climbing' | 'thinking' | 'believing' | 'knowing' | 'understanding' | 'making' | 'fixing' | 'playing' | 'touching' | 'picking' | 'putting' | 'taking' | 'remembering' | 'forgetting' | 'pushing' | 'pulling' | 'shaking' | 'baking' | 'cooking' | 'driving' | 'riding' | 'buying' | 'selling' | 'lending' | 'borrowing' | 'stealing' | 'tearing' | 'opening' | 'closing' | 'walking' | 'sitting' | 'standing' | 'resting' | 'working' | 'waiting' | 'hoping' | 'dreaming' | 'moving' | 'reflecting' | 'looking' | 'listening' | 'hearing'
    PastParticiple -> 'eaten' | 'run' | 'jumped' | 'seen' | 'written' | 'read' | 'drunk' | 'spoken' | 'slept' | 'created' | 'built' | 'loved' | 'hated' | 'helped' | 'caught' | 'thrown' | 'found' | 'lost' | 'drawn' | 'painted' | 'taught' | 'studied' | 'laughed' | 'cried' | 'sung' | 'danced' | 'climbed' | 'thought' | 'believed' | 'known' | 'understood' | 'made' | 'fixed' | 'played' | 'touched' | 'picked' | 'put' | 'taken' | 'remembered' | 'forgotten' | 'pushed' | 'pulled' | 'shaken' | 'baked' | 'cooked' | 'driven' | 'ridden' | 'bought' | 'sold' | 'lent' | 'borrowed' | 'stolen' | 'torn' | 'opened' | 'closed' | 'walked' | 'sat' | 'stood' | 'rested' | 'jumped' | 'worked' | 'waited' | 'hoped' | 'dreamed' | 'moved' | 'reflected' | 'looked' | 'listened' | 'heard' | 'slept'
    SingularAux -> 'is'
    PluralAux -> 'are'
    pastparticipleAUXP -> 'have'
    pastparticipleAUXS -> 'has'
    Article -> 'the' | 'a' | 'an'
    Adjective -> 'big' | 'small' | 'beautiful' | 'ugly' | 'fast' | 'slow' | 'happy' | 'sad' | 'young' | 'old' | 'new' | 'good' | 'bad' | 'easy' | 'hard' | 'bright' | 'dark' | 'strong' | 'weak' | 'clean' | 'dirty' | 'expensive' | 'cheap' | 'tall' | 'short' | 'intelligent' | 'funny' | 'kind' | 'rude' | 'generous' | 'selfish' | 'rich' | 'poor' | 'tired'
    Adverb -> 'quickly' | 'slowly' | 'silently' | 'loudly' | 'happily' | 'sadly' | 'easily' | 'hardly' | 'brightly' | 'darkly' | 'strongly' | 'weakly' | 'cleanly' | 'dirtily' | 'expensively' | 'cheaply' | 'intelligently' | 'kindly' | 'rudely' | 'generously' | 'selfishly' | 'beautifully'
    """)


data = {
    "SingularPronoun": [["he"], ["she"], ["it"]],
    "PluralPronoun": [["they"]],
    "SingularNoun": [["John"], ["Mary"], ["dog"], ["cat"], ["water"], ["bread"], ["juice"], ["milk"], ["house"], ["car"], ["apple"]],
    "PluralNoun": [["dogs"], ["cats"], ["waters"], ["breads"], ["juices"], ["milks"], ["houses"], ["cars"], ["apples"]],
    "PluralVerb": [
        ["eat"], ["run"], ["jump"], ["see"],
        ["write"], ["read"], ["drink"], ["speak"], ["sleep"],
        ["create"], ["build"], ["love"], ["hate"], ["help"], ["catch"], ["throw"], ["find"], ["lose"],
        ["draw"], ["paint"], ["teach"], ["study"], ["laugh"], ["cry"], ["sing"], ["dance"], ["climb"], ["run"],
        ["think"], ["believe"], ["know"], ["understand"], ["make"], ["fix"], ["write"], ["play"], ["touch"],
        ["pick"], ["put"], ["take"], ["remember"], ["forget"], ["help"], ["push"], ["pull"], ["shake"],
        ["bake"], ["cook"], ["drive"], ["ride"], ["buy"], ["sell"], ["lend"], ["borrow"], ["steal"],
        ["build"], ["tear"], ["open"], ["close"], ["run"], ["walk"], ["sit"], ["stand"], ["rest"], ["jump"],
        ["work"], ["sleep"], ["wait"], ["hope"], ["dream"], ["tear"], ["touch"], ["move"], ["speak"],
        ["read"], ["write"], ["reflect"], ["look"], ["see"], ["think"], ["listen"], ["hear"]
    ],
    "Adjective": [
        ["big"], ["small"], ["beautiful"], ["ugly"], ["fast"], ["slow"], ["happy"], ["sad"],
        ["young"], ["old"], ["new"], ["good"], ["bad"], ["easy"], ["hard"], ["bright"], ["dark"],
        ["strong"], ["weak"], ["clean"], ["dirty"], ["expensive"], ["cheap"], ["tall"], ["short"],
        ["intelligent"], ["funny"], ["kind"], ["rude"], ["generous"], ["selfish"], ["rich"], ["poor"], ["tired"]
    ],

    "Adverb":[["quickly"], ["slowly"], ["silently"], ["loudly"], ["happily"], ["sadly"],
         ["easily"], ["hardly"], ["brightly"], ["darkly"], ["strongly"], ["weakly"],
         ["cleanly"], ["dirtily"], ["expensively"], ["cheaply"], ["intelligently"],
         ["funny"], ["kindly"], ["rudely"], ["generously"], ["selfishly"], ["beautifully"]]
}


nltk_parser = nltk.ChartParser(nltk_grammar)
pda = PDASimulator()

def validate_sentence(sentence):
        print(f"\n Sentence: '{sentence}'")
        tokens = sentence.split()
        print(f"🔹 Tokens: {tokens}\n")

        accepted = pda.parse(tokens)
        print(" PDA Accepted" if accepted else "❌ PDA Rejected")

        parse_tree_shown = False
        try:
           for tree in nltk_parser.parse(tokens):
            if accepted:
                print("\n Parse Tree:")
                tree.pretty_print()
            parse_tree_shown = True
            break
        except ValueError:
         pass

        if accepted and parse_tree_shown:
          print(" Valid Sentence\n")
        else:
          print(" Invalid Sentence\n")


sentences = [
     "John eats",
     "they eat",
     "she runs",
     "they runs",
     "he is running",
     "they are running",
     "Mary are running",
     "cats jump",
     "it jump",
     "he is writing",
     "they are reading",
     "John is jumping",
     "cats are drinking",
     "she is speaking",
     "they are speaking",
     "it is sleeping",
     "he drinking",
     "they drink",
     "she drinks",
     "they drink water",
      "John has eaten",
     "they have eaten",
     "she has written",
     "they have run",
     "he has eaten an apple",
     "they have eaten apples",
     "she have eaten",
     "he have written",
     "they has eaten",
     "John has jump",
     "he has eaten big apples",
    "John has eating",
    "he is eaten",
    "the tired cat has slept",
    "the tired dog has run",
    "they are eaten",
    "the tired dogs have run",
    "he has written quickly",
    "they have written slowly",
    "she has beautifully sung",
    "he have slept",
    "John has tired",
    "John is quickly running",
    "John is running silently"
]


def get_user_choice(prompt):
    """Helper to get clean y/n input from user."""
    while True:
        choice = input(prompt).strip().lower()
        if choice in ('y', 'n'):
            return choice
        print("Invalid choice. Please type 'y' or 'n'.")

print("Checking pre-defined sentences:\n")

for s in sentences:
    validate_sentence(s)


if get_user_choice("\nDo you want to check more sentences? (y/n): ") == 'y':
    print("\nInstructions:")
    print("- Type a full sentence you want to validate.")
    print("- Only capitalize the first letter of names (John, Mary). Everything else should be in small case")
    print("- Use proper grammar (subject + verb + object, if needed).")
    print("- No need for punctuation.")
    print("- Complex sentences such as compound sentences and present perfect continuous sentences are not allowed.")
    print("- Sentences should be similar in structure to the pre-defined sentences.")
    print("- Only make sentences using the vocabulary provided below.\n")

    for key, values in data.items():
        words = [item[0] for item in values]
        print(f"{key}: {', '.join(words)},")


    while True:
        user_sentence = input("\nEnter your sentence: ").strip()
        validate_sentence(user_sentence)

        if get_user_choice("\nDo you want to enter another sentence? (y/n): ") == 'n':
            print("\nExiting user sentence input...\n")
            break

print("\nExiting the program. Goodbye!\n")